rocketmq:
        accessKey: xxx
        secretKey: xxx
        nameSrvAddr: xxx1
        topic: xxx
        groupId: xxx
        tag: a
        orderTopic: XXX
        orderGroupId: XXXw
        orderTag: a

aliyun:
        accessId: x
        accessKey: x
        aliyunId: x
        validityTime: 240
server:
        port: 8009